### PR TITLE
Feature/507

### PR DESCRIPTION
**Pull request by Minyahil40**
This PR is for google sign in support.

### CODE REVIEW

**Comment by shaneknows** [comment]
image
Is this how it is supposed to look? Seems incorrect to me as it still needs an email address either way

**Comment by Minyahil40** [comment]
> 
@shaneknows 
the option to login with email and password is still works

**Review by shaneknows — CHANGES_REQUESTED** [review]
Getting an error linking my google account (using the apk artifact from the build). Not really sure what the issue is.
image

**Comment by Minyahil40** [comment]
@shaneknows  the email option?

**Comment by Minyahil40** [comment]
I'll check if any google configuration is missing. can you check the regular email login?

**Comment by shaneknows** [comment]
> I'll check if any google configuration is missing. can you check the regular email login?

Yeah the regular login still works.

**Review by lwvantassel — DISMISSED** [review]

**Comment by shaneknows** [comment]
> 

Any update on this? If we can get the logins to work and still supply an email for IMAP to fetch, this is worth getting in, but if its just a matter of logging in with no email access we may want to drop this feature.

**Pull request closed without merging**
